JustaPenguin/assetto-server-manager

- championship_manager.go
- championship_manager_test.go
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- entrylist_ini.go
- fixtures/open-championship-test.json
- fixtures/open-championship/championship-setup.json
- fixtures/open-championship/nurburgring_sprint_b.json
- fixtures/open-championship/rbr_national.json
- fixtures/open-championship/suzuka_east.json
- fixtures/results/2019_3_2_14_41_PRACTICE.json
- fixtures/results/2019_3_2_17_27_PRACTICE.json
- fixtures/results/2019_3_2_19_30_PRACTICE.json
- fixtures/results/2019_3_2_20_48_QUALIFY.json
- fixtures/results/2019_3_2_21_21_QUALIFY.json
- fixtures/results/2019_3_2_21_36_RACE.json
- fixtures/results/2019_3_2_21_49_QUALIFY.json
- fixtures/results/2019_3_2_21_4_RACE.json
- fixtures/results/2019_3_2_22_15_QUALIFY.json
- fixtures/results/2019_3_2_22_28_RACE.json
- fixtures/results/2019_3_2_22_3_RACE.json
- templates.go
* fixes issues with class/car switching within championship events causing duplicate entrants
* sorts the championship entrant tables and tidies them up, adding colour coding and classes
* empty drivers are filtered out of the entrant table and a 'n open slots' message is displayed instead
* car listings in championship pages now use the ValidCarIDs on the championship
* the open championship option now persists correctly
> various open championship fixes

- cmd/server-manager/static/css/style.css
Just another little change to improve live map visualisation by removing the gray background and applying some `drop-shadow` to track outline.
> Remove gray background and add some shadow to track outline

- CHANGELOG.md
- cmd/server-manager/javascript/manager.js
> pad millisecond values in msToTime to prevent misleading best lap times

- server_process_windows.go
It only makes things messier and it can fail. A single taskkill command just works.
> Don't use process.Kill() at all on Windows while killing processes

- cmd/server-manager/typescript/src/javascript/manager.js
- cmd/server-manager/views/pages/championships/view.html
removes team names from championship event points tables if nobody in the championship has a team name (fixes #417, fixes #418)
> fixes popovers so they work with the new bootstrap update

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
- content_manager_wrapper.go
- server_process.go
> on client disconnect, if the driver has no loaded time, remove them from the connected drivers table

- CHANGELOG.md
- championships.go
- championships_test.go
- entrylist_ini.go
prevents mismatching entrant data when assigning slots
fixes #441
> open championships: swap the assigned entrant with the free entrant slot when adding entrants to the Championship entrylist 

- cmd/server-manager/views/pages/custom-race/new.html
- config_ini.go
- race_manager.go
The issue comes directly from Kunos, there's not much we can do. Kunos is not dropping any further AC updates anyway.
We pretty much confirmed both options have their own different problems, at this point letting the user decide which setting to go for is the best option, IMO.
> cj123/assetto-server-manager#271: Allow users to set LOCKED_ENTRY_LIST and PICKUP_MODE separately as they want

- content_setups.go
I have three ASM servers, which share a common setup folder using symlinks from each server's assetto folder ...
shared/setups
server1/assetto
server1/assetto/setups => shared/setups
server2/assetto
server2/assetto/setups => shared/setups
server3/assetto
server3/assetto/setups => shared/setups
Ran into an issue with the car setups code, which uses filepath.Walk() on the setups path ... and filepath.Walk() doesn't traverse symlinks.  So no setups show for any cars, although they can be uploaded.
The fix seems to be to de-reference the setup path with EvalSymlinks() when reading the setups, which returns the path unchanged if it's not a symlink, or the target path if it is.
Tested on Ubuntu and Windows 10 (soft links), with and without setup path being a link.
> Check for symlink in car setups

- content_cars.go
The content folder on my league server has no skins folders for cars, as they haven't been needed in the past.  So I get hundreds of basically spurious log msgs warning me about not being able to load skins, which keep repeating.
This PR simply creates an empty skins folder if one doesn't exist, cutting down on constant naggy warnings.
> Create empty skins folder if it doesn't exist

- content_setups.go
- entrylist_ini.go
This PR adds a couple of checks so that if there are stray setup files at the root of the setups folder, it doesn't potentially break things.  Not likely to happen, but in my specific use case I share a setup folder with some other (non server-manager) provisioning, which has setup files at the root.  This confused SM, and led to a situation where a race would fail silently.
These two checks should a) prevent those from being shown in the race setup in the first place, and b) prevent problems if a previously uploaded setup was deleted, but still in use in a race config.
> Couple of sanity checks on setup files

- content_manager_wrapper.go
Quick fix to avoid showing non-useful string in Content Manager.
Steps followed:
- Add a download URL in a track's metadata and save.
- Remove the previously added download URL.
- Start a session.
- Content Manager shows track's download string without content.
> Avoid printing track's downloadURL if empty

- CHANGELOG.md
- race_manager.go
for races with recurrence rules with UNTIL/COUNT specified
> prevent recursive call to FindNextOccurrence when the next occurence is a zero-time 

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/results/result.html
- cmd/server-manager/views/partials/results/session-overall.html
- penalties.go
- race_weekend_sort.go
- results.go
most results functions now require a car model alongside a driver's guid. this is so that if a driver is in a results file N times (in different cars) statistics are correctly reported for each car
fixes #637
> results improvements: car swapping

- CHANGELOG.md
- cmd/server-manager/config.example.yml
- server_process.go
- servermanager_config.go
(fixes an issue where plugins with spaces in their paths not start)
> deprecate run_on_start, add plugins to server options, with more specific separation of executable and arguments

- championship_manager_test.go
- discord.go
- go.mod
- go.sum
- notification_manager.go
Separates Discord 'embed' messages into title and message, as you can't have markdown links in the title.  When group tagging notifications are enabled, adds the title to the notification  (the part which shows in the actual notification on phones), like "Attention @notifications - race start in X minutes", rather than just "Attention @notifications".  With notifications disabled, inserts it as the 'title' part of the embed.
Added durafmt library, as it turns out formatting a length of time in human readable format in Go is not trivial.
> Improving message formatting, issues with download links

- cmd/server-manager/views/pages/server/logs.html
- router.go
- server_administration.go
Proposal to address #426, please let me know if this is in line with what you imagined here.
----
Adds a new API endpoint `/api/log-download/{logFile}` and according handler in `ServerAdministratorHandler` which accepts one of the parameters `ServerLog`, `ManagerLog`, and `PluginsLog` (returns 404 otherwise), as well as download buttons linking to each individual logfile on the `/logs` page.
Currently returns each log as a plain text file including the current time in RFC3339 format in the file name, for example `ServerLog_2020-01-31T14_35_07Z.log`.
The new download buttons can be found below each log:
> Add buttons & API endpoints for server log downloads

- router.go
chi middleware compress no longer has the DefaultCompress function as it was marked deprecated and is now removed. See https://github.com/go-chi/chi/commit/baf4ef5b139e284b297573d89daf587457153aa3.
I have replaced the previous use of DefaultCompress with the equivalent using compress and tested to ensure that the same file types are being sent with compression.
> Changed DefaultCompress as it was previously deprecated and now removed

- content_cars.go
Fixes https://github.com/JustaPenguin/assetto-server-manager/issues/848.
I have two commits in here, which could certainly be squashed; in the first commit I've included comments referencing evidence of the `.kn5` files appearing in the DLC packages themselves.
> Corrections to some cars "DLC" identification status

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
- cmd/server-manager/typescript/src/models/RaceControl.ts
- cmd/server-manager/views/pages/custom-race/new.html
- content_cars.go
- pkg/udp/model.go
- race_control.go
- servermanager_config.go
fix an issue where a car that has completed no laps would remain in live timings. set same-site mode for cookie store sessions. remove useless error message when creating car skin directories
> use correct car name in live timings (+other misc fixes)

- CHANGELOG.md
- content_cars.go
> remove watcher limits on car scanning, so multiple cars added at once are detected correctly

- server_process.go
- server_process_nonwindows.go
- server_process_windows.go
Refactor the plugin kill call to try a SIGINT for some time then use
SIGKILL as required.  In all cases a cmd.Wait is called which ensures
the process is reaped (e.g no defunct procs).
This change mitigates a plugin restart race conditions where the process
being killed is not fully shutdown before a new one is started.  Ie. Issues
with TCP port bind() calls failing when an existing process was not fully terminated.
Related to #1030 
NOTES: Untested in Windows
DISCLAIMER: My first attempt at using golang.
> Graceful plugin and acServer shutdown.

- Makefile
Without this change I am unable to build the project (docker image) without a timeout error on a nuc.
> Increase timeout for building on slower devices
