- cars.go
- cmd/server-manager/main.go
- config_ini.go
- form.go
- handlers.go
> added car list, multiselect with persistence

- config_ini.go
- config_ini_default.go
- handlers.go
- tracks.go
> Populated track list, tracks correctly identify and store layouts

- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/content/tracks.html
- cmd/server-manager/views/pages/content/weather.html
- cmd/server-manager/views/pages/results/result.html
- entrylist_ini.go
- results.go
- templates.go
> progress bar

- cmd/server-manager/static/manager.js
> added simple log char limit, could be made configurable? Or turn on/off

- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/custom-race/new.html
- config_ini.go
- content_weather.go
- race_manager.go
> Enable and configure sol weathers

- cmd/server-manager/static/css/style.css
- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/content/tracks.html
- cmd/server-manager/views/pages/content/weather.html
- handlers.go
> added drag and drop for all content types

- cmd/server-manager/views/pages/custom-race/new.html
- config_ini_default.go
> remove double negative from race gas penalty, change default to OFF

- cmd/server-manager/static/css/style.css
- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/championships/new.html
- cmd/server-manager/views/pages/custom-race/new.html
- cmd/server-manager/views/pages/quick_race.html
- config_ini.go
move navigate-away code to target forms with attribute data-safe-submit (fixes #53)
> add the ability to add many entrants at once

- cmd/server-manager/static/css/style.css
- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/championships/new.html
- cmd/server-manager/views/pages/custom-race/new.html
- cmd/server-manager/views/pages/quick_race.html
- config_ini.go
- content_tyres.go
- race_manager.go
fixes #56.
do other PR first ;P
> Track grip presets

- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/custom-race/new.html
- cmd/server-manager/views/pages/quick_race.html
> add time of day and sun angle calculations for non-sol weathers

- cmd/server-manager/static/css/style.css
- cmd/server-manager/static/manager.js
- cmd/server-manager/views/pages/custom-race/new.html
- config_ini.go
- config_ini_default.go
fix some help text in custom race + server config
> change default start rule to drive through

- cmd/server-manager/views/pages/championships/new.html
- cmd/server-manager/views/pages/custom-race/new.html
- cmd/server-manager/views/pages/quick_race.html
- race_manager.go
> Sol start time

- cmd/server-manager/views/pages/custom-race/new.html
> better message about no join, hide options when required

- .gitignore
- championship_manager.go
- championship_manager_test.go
- championships.go
- championships_test.go
- cmd/server-manager/run.sh
- cmd/server-manager/views/pages/championships/new.html
- entrylist_ini.go
- fixtures/barbagello-no-end-sessions.json
- fixtures/barbagello.json
- fixtures/formula4-championship.json
- fixtures/red-bull-ring.json
- live_timings.go
- pkg/udp/messages.go
- pkg/udp/model.go
- race_manager.go
- race_store.go
- race_store_json.go
> add 'open championships' where entrants can join races to be added to the championship entrylist

- championships.go
- cmd/server-manager/views/pages/championships/view.html
> championship points now apply correctly to multiclass races

- penalties.go
- results.go
> penalties of more than one lap duration now take laps off

- CHANGELOG.txt
- README.md
- cmd/server-manager/config.example.yml
- cmd/server-manager/views/pages/quick_race.html
- cmd/server-manager/views/partials/results/session-overall.html
- results.go
> change result average lap calculation. fix quick race time/lap bug

- CHANGELOG.txt
- championship_manager.go
- championship_manager_test.go
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/partials/championships/class.html
- config_ini.go
- race_manager.go
- templates.go
> reverse grid position championship support

- cmd/server-manager/javascript/manager.js
- cmd/server-manager/views/pages/results/result.html
> added open in simresults button to results pages

- CHANGELOG.txt
- cmd/server-manager/javascript/manager.js
- content_tracks.go
> add support for tracks with extra layouts other than the default 

- cmd/server-manager/views/layout/base.html
- templates.go
> show build version in footer

- CHANGELOG.txt
- championship_manager.go
- cmd/server-manager/views/pages/championships/index.html
> sort championships by active/inactive, and last updated date

- README.md
* Add port-forwarding for 9600/udp.
* Wrap ports in quotes according to docker-documentation.
> #164: Improve docker-compose.yml-example

- CHANGELOG.txt
- championship_manager.go
- championships.go
- cmd/server-manager/javascript/manager.js
- cmd/server-manager/views/pages/championships/new.html
- cmd/server-manager/views/pages/championships/view.html
> added ability to add links to a championship

- CHANGELOG.txt
- cmd/server-manager/javascript/manager.js
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/content/tracks.html
- cmd/server-manager/views/pages/content/weather.html
> added ability to upload multiple folders to drag and drop

- CHANGELOG.txt
- championship_manager.go
- race_manager.go
> save entrant details for autofill on championship create as well

- championship_manager.go
- championship_manager_test.go
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/home.html
- cmd/server-manager/views/pages/live-timing.html
- go.mod
- race_manager.go
- server_process.go
- server_process_windows.go
- templates.go
> improve championship event starting/stopping

- CHANGELOG.txt
- cmd/server-manager/javascript/manager.js
> Quick race mobile safari

- CHANGELOG.txt
- cmd/server-manager/javascript/manager.js
- cmd/server-manager/views/partials/race-builder/entrant.html
- content_setups.go
> entrant autocomplete now also available through a dropdown

- CHANGELOG.txt
- championship_manager.go
- cmd/server-manager/.gitignore
- handlers.go
- race_manager.go
- server_process_windows.go
> championship fixes

- championship_manager.go
- race_custom.go
- race_manager.go
> fixed my silly timer function not being cancelled

- CHANGELOG.md
- cmd/server-manager/static/css/style.css
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/content/tracks.html
- cmd/server-manager/views/pages/home.html
- cmd/server-manager/views/pages/server/blacklist.html
- handlers.go
> Blacklist editor

- live_timings.go
> added a detection system for missed car updates

- CHANGELOG.md
- championship_manager.go
- cmd/server-manager/views/partials/results/session-overall.html
> penalties can now correctly be applied to imported championship events

- CHANGELOG.md
- championship_manager.go
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/partials/results/session-overall.html
- handlers.go
> championship drivers and teams can now have points penalties

- CHANGELOG.md
- championship_manager.go
- championships.go
- cmd/server-manager/views/pages/championships/import.html
- live_timings.go
- results.go
> results import on open championships now populates the entrylist of new drivers (if space is available)

- CHANGELOG.md
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/pages/custom-race/new.html
> improve 2nd race reverse text when its value is '1'

- CHANGELOG.md
- race_manager.go
> force loop mode to ON for looped races

- CHANGELOG.md
- championships.go
- cmd/server-manager/javascript/manager.js
- cmd/server-manager/views/pages/championships/view.html
- handlers.go
- results.go
> added championship simresults export

- CHANGELOG.md
- championship_manager.go
- championships.go
- cmd/server-manager/views/pages/championships/import_championship.html
- cmd/server-manager/views/pages/championships/index.html
- handlers.go
> added championship importer

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/championships/sign-up.html
- pkg/udp/model.go
> improve open championship/sign up form car allocation so that slots in the entrylist are respected instead of replaced or removed

- CHANGELOG.md
- cmd/server-manager/static/css/style.css
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/live-timing.html
- handlers.go
- templates.go
> implement live map smoothing as per #320, with transition interval matching live map refresh interval

- CHANGELOG.md
- championship_manager.go
- cmd/server-manager/views/pages/championships/view.html
- templates.go
> improve championship 2nd race detection

- CHANGELOG.md
- championship_manager.go
- cmd/server-manager/views/pages/custom-race/new.html
- config_ini.go
> locked entry list, pickup mode, championship events with booking

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/championships/view.html
> hide team standings when no entrants in a championship have a team name

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/championships/sign-up.html
- cmd/server-manager/views/pages/championships/signed-up-entrants.html
- cmd/server-manager/views/pages/championships/view.html
> allow for deletion of championship signup entrants

- cmd/server-manager/config.example.yml
Improved and more clear instructions on how to configure plugins. Also added KMR plugin configuration instructions
> Plugin configuration documentation

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/partials/results/session-overall.html
> add per-event points breakdowns to championships (fixes #368)

- CHANGELOG.md
- live_timings.go
> only count a lap as best if it has no cuts (fixes #363)

- cmd/server-manager/config.example.yml
They are not written in the config.yml, so I guess we should add them 🤷‍♂
> Config.yml: tell users the default credentials

- CHANGELOG.md
- cmd/server-manager/views/pages/custom-race/new.html
- config_ini.go
- content_tracks.go
- race_manager.go
> add an option to disable DRS for any track via custom race / championship event forms

- CHANGELOG.md
- championships.go
- championships_test.go
> don't empty out open championship entrant team names if they are not being replaced by a new team name

- CHANGELOG.md
- accounts.go
- audit_log.go
- cmd/server-manager/config.example.yml
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/server/audit-logs.html
- handlers.go
- migrations.go
- race_manager.go
- servermanager_config.go
- store.go
- store_bolt.go
- store_json.go
> Audit logs

- championships.go
- migrations.go
- race_custom.go
- race_manager.go
- scheduled_races.go
- server_process_windows.go
run championship pitbox migrations on event entrylists, not championship combined entry lists. add pitboxes to quick race entrants (fixes #401)
> entrant pitbox fix for quick race + existing championship events

- Makefile
- README.md
- cmd/server-manager/Makefile
> added make assets-embed to make file(s). Added build instructions

- scheduled_races.go
- server_administration.go
> Motd word wrap

- CHANGELOG.md
- cmd/server-manager/typescript/package-lock.json
- cmd/server-manager/typescript/package.json
- cmd/server-manager/typescript/src/RaceControl.ts
> reconnect websocket if connection drops

- CHANGELOG.md
- entrylist_ini.go
> Entry list sort

- CHANGELOG.md
- cmd/server-manager/views/pages/custom-race/new.html
> fix an issue where session time/laps did not correctly display

- cmd/server-manager/views/pages/championships/view.html
> only show view in simresults if championship progress > 0

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
- cmd/server-manager/typescript/src/models/RaceControl.ts
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/custom-race/index.html
- cmd/server-manager/views/pages/custom-race/new.html
- race_control.go
> Race control scroll jump

- CHANGELOG.md
- cmd/server-manager/views/pages/custom-race/new.html
- race_manager.go
> use UTC timezone for all sol times

- content_manager_wrapper.go
- discord.go
- notification_manager.go
- race_control_http.go
- resolver.go
- scheduled_races.go
fixing import loops and the need to pass the resolver to a manager's constructor
> extract common methods from ScheduledRacesHandler into ScheduledRacesManager

- discord.go
- notification_manager.go
Also added env var for notification test mode.
> Fix for ipv6 addresses messing up Discord embeds

- CHANGELOG.md
- cmd/server-manager/views/pages/championships/view.html
> always show championships entrants tab

- CHANGELOG.md
- cmd/server-manager/main.go
- cmd/server-manager/typescript/src/RaceControl.ts
- cmd/server-manager/views/pages/live-timing.html
- cmd/server-manager/views/pages/results/result.html
- config_ini.go
- race_control_http.go
- resolver.go
- results.go
- templates.go
> added a global option to switch from km/h to mph

- CHANGELOG.md
- championship_manager_test.go
- cmd/server-manager/typescript/sass/_race-weekend.scss
- cmd/server-manager/typescript/src/javascript/manager.js
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/race-weekend/view.html
- init.go
- notification_manager.go
- race_weekend.go
- race_weekend_handler.go
- race_weekend_manager.go
- resolver.go
- router.go
- scheduled_races.go
> race weekend session scheduling

- CHANGELOG.md
- championship_manager.go
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/partials/championships/points.html
- race_weekend_manager.go
- results.go
> Championship points modifiers

- CHANGELOG.md
- cmd/server-manager/typescript/sass/_results.scss
- cmd/server-manager/typescript/src/Results.ts
- cmd/server-manager/typescript/src/javascript/manager.js
- cmd/server-manager/typescript/src/main.ts
- cmd/server-manager/views/pages/results/result.html
- content_tracks.go
- results.go
- router.go
> added collision maps to results event tab

- results.go
> improved sorting algorithm for fastest lap

- CHANGELOG.md
- cmd/server-manager/typescript/sass/_championships.scss
- cmd/server-manager/views/pages/championships/view.html
> added a height limit to championship standings/entrants tables

- CHANGELOG.md
- cmd/server-manager/views/pages/content/track-details.html
- content_tracks.go
> Track page title

- CHANGELOG.md
- cmd/server-manager/typescript/sass/_custom-race.scss
- cmd/server-manager/typescript/sass/server-manager-dark.scss
- cmd/server-manager/views/pages/content/car-details.html
- cmd/server-manager/views/pages/content/cars.html
- cmd/server-manager/views/pages/content/track-details.html
- cmd/server-manager/views/pages/content/tracks.html
…about car/track origin to both list and detail pages
Fixes #593
> Dlc mod cars dark mode

- CHANGELOG.md
- accounts.go
- cmd/server-manager/views/pages/accounts/manage.html
> stopped users from deleting their own accounts, both front and backend

- CHANGELOG.md
- cmd/server-manager/views/pages/race-weekend/view.html
- race_weekend_manager.go
> improve entrylist handling when starting race weekend practice sessions

- CHANGELOG.md
- championship_manager.go
- championships_handler.go
- cmd/server-manager/Makefile
- cmd/server-manager/main.go
- cmd/server-manager/typescript/sass/_layout.scss
- cmd/server-manager/views/layout/base.html
- config_ini.go
- content_cars.go
- healthcheck.go
- init.go
- migrations.go
- race_manager.go
- race_weekend.go
- race_weekend_manager.go
- resolver.go
- router.go
- scheduled_races.go
- server_process_nonwindows.go
- server_process_windows.go
- servermanager_config.go
> multiserver tool compatibility

- CHANGELOG.md
- cmd/server-manager/config.example.yml
- cmd/server-manager/typescript/src/javascript/manager.js
- content_cars.go
- store_json.go
> accounts are now in shared stores, championships can be edited in multiserver, reverted back to bolt search index

- CHANGELOG.md
- cmd/server-manager/views/pages/content/track-details.html
- race_manager.go
> fixes an issue where track details pages could crash

- CHANGELOG.md
- content_cars.go
- race_manager.go
> any available car now makes sure there is one of each car in the entrylist before randomising cars

- CHANGELOG.md
- cmd/server-manager/views/layout/base.html
> display a server name without a tooltip on mobile devices

- CHANGELOG.md
- cmd/server-manager/typescript/src/javascript/manager.js
> encodeURIComponent on car and skin names when showing the skin preview image

- cmd/server-manager/views/pages/quick-race.html
> remove completely unnecessary variable from quick race page

- CHANGELOG.md
- championships_handler.go
- race_weekend_handler.go
> admins can now see championship sign up responses in the export

- acsr.go
- championship_manager.go
- championship_manager_test.go
- config_ini.go
- form.go
- race_weekend_manager.go
- resolver.go
- server_administration.go
- servermanager_config.go
> acsr key and account id are now configured in server options

- cmd/server-manager/typescript/sass/_home.scss
- cmd/server-manager/typescript/src/Font.ts
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/pages/premium.html
- cmd/server-manager/views/partials/premium.html
- cmd/server-manager/views/partials/race-weekend-premium.html
- router.go
- server_administration.go
> add acsr championship indicator, server manager premium information page

- CHANGELOG.md
- championship_manager_test.go
- championships.go
- cmd/server-manager/views/pages/custom-race/new.html
- race_custom.go
- race_event.go
- race_manager.go
- race_quick.go
- race_weekend.go
- resolver.go
> Force stop timer

- CHANGELOG.md
- championship_manager.go
- championships.go
- championships_handler.go
- cmd/server-manager/views/pages/custom-race/new.html
- content_cars.go
- init.go
- migrations.go
- race_weekend.go
- race_weekend_handler.go
- race_weekend_manager.go
- resolver.go
- server_process.go
> fix championship class IDs colliding on championships

- CHANGELOG.md
- championship_manager.go
- server_process.go
- store_bolt.go
- store_json.go
> improve handling of server stop to make batch files stop correctly on windows

- CHANGELOG.md
- championship_manager.go
- championships.go
- cmd/server-manager/views/pages/custom-race/new.html
> correctly apply pitbox for sign up form championships by using AddInPitBox not Add

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/custom-race/new.html
- init.go
> don't say 'first event of the championship' if there's only one event in the championship

- server_process.go
Changed line 344 ACServerResultsBasePath to correct ServerInstallpath
> Kissmyrank results

- CHANGELOG.md
- results.go
> check guid and car model when getting drivers best lap tyre

- CHANGELOG.md
- championships.go
- penalties.go
> only try to match session files if the session has been completed

- CHANGELOG.md
- cmd/server-manager/views/pages/race-weekend/popups/manage-filters.html
> hide start on tyre from fastest lap checkbox for non-write users

- CHANGELOG.md
- championship_manager.go
> specific handling of entrants team changing for race weekends in championships

- CHANGELOG.md
- championships.go
> don't apply points penalties to points for individual events

- CHANGELOG.md
- cmd/server-manager/views/partials/championships/event-card.html
> allow duplication of completed championship events

- CHANGELOG.md
- cmd/server-manager/typescript/src/javascript/manager.js
> only call multiselect('refresh') once per populateTyreDropdown

- CHANGELOG.md
- plugin_kissmyrank_config.go
> add compatibility for KMR v1.6f

- CHANGELOG.md
- cmd/server-manager/plugins/json.lua
- cmd/server-manager/plugins/utils.lua
- cmd/server-manager/views/pages/custom-race/new.html
> fixed lua empty maps being returned as empty arrays by lua json encode

- config_ini.go
> hide content manager wrapper port setting for hosted users (fixes #834)

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
- cmd/server-manager/views/pages/live-timing.html
- race_control_http.go
- router.go
> added broadcast countdown to admin panel

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceWeekend.ts
- cmd/server-manager/views/pages/race-weekend/popups/manage-filters.html
- race_weekend_filter.go
- race_weekend_handler.go
> it is now possible to choose specific drivers when filtering between race weekend sessions

- CHANGELOG.md
- cmd/server-manager/views/pages/race-weekend/view.html
- cmd/server-manager/views/partials/championships/raceweekend-card.html
> race weekend sessions now indicate if a race has +1 lap

- config_ini.go
- migrations.go
> force logging on, and hide, for hosted instances

- CHANGELOG.md
- championship_manager.go
- championships_handler.go
- cmd/server-manager/views/pages/championships/index.html
- router.go
> added the ability to duplicate championships

- CHANGELOG.md
- championship_manager.go
- championships_handler.go
- cmd/server-manager/typescript/sass/_championships.scss
- cmd/server-manager/views/pages/championships/index.html
- cmd/server-manager/views/pages/race-weekend/view.html
- cmd/server-manager/views/partials/championships/event-card.html
- cmd/server-manager/views/partials/championships/raceweekend-card.html
- race_weekend.go
> Championship race weekend complete date

- CHANGELOG.md
- championship_manager.go
- championships.go
- content_manager_wrapper.go
- race_control.go
- race_weekend.go
- race_weekend_manager.go
- resolver.go
- store.go
- store_bolt.go
- store_json.go
> show championship details in race weekends, greet users with championship message in race weekends

- CHANGELOG.md
- championships.go
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/partials/championships/overview.html
- race_control_http.go
- templates.go
> Championship overview

- CHANGELOG.md
- championship_manager.go
- cmd/server-manager/typescript/sass/_custom-race.scss
- cmd/server-manager/typescript/sass/_race-control.scss
- cmd/server-manager/typescript/src/Championship.ts
- cmd/server-manager/typescript/src/RaceList.ts
- cmd/server-manager/typescript/src/RaceWeekend.ts
- cmd/server-manager/typescript/src/javascript/manager.js
- cmd/server-manager/typescript/src/main.ts
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/championships/view.html
- cmd/server-manager/views/pages/custom-race/index.html
- cmd/server-manager/views/pages/custom-race/new.html
- cmd/server-manager/views/pages/custom-race/popups/view.html
- cmd/server-manager/views/pages/home.html
- cmd/server-manager/views/pages/race-weekend/view.html
- cmd/server-manager/views/partials/championships/event-card.html
- config_ini.go
- config_ini_default.go
- content_manager_wrapper.go
- content_tracks.go
- migrations.go
- race_custom.go
- race_manager.go
- resolver.go
- router.go
- templates.go
> race details popup

- CHANGELOG.md
- cmd/server-manager/typescript/package-lock.json
- cmd/server-manager/typescript/package.json
- cmd/server-manager/views/pages/results/combine.html
- cmd/server-manager/views/pages/results/index.html
- race_control.go
- results.go
- router.go
> combine results added

- CHANGELOG.md
- championship_manager.go
- cmd/server-manager/main.go
- lua.go
- race_manager.go
- race_weekend_manager.go
- results.go
> each plugin run now has its own lua state. force a 30 second result time on championship practice sessions

- CHANGELOG.md
- cmd/server-manager/typescript/src/Font.ts
- cmd/server-manager/views/layout/base.html
- cmd/server-manager/views/pages/home.html
- cmd/server-manager/views/pages/server/current-config.html
- cmd/server-manager/views/pages/server/logs.html
- config_ini.go
- entrylist_ini.go
- router.go
- server_administration.go
> View current cfg

- CHANGELOG.md
- cmd/server-manager/typescript/src/javascript/manager.js
- cmd/server-manager/views/pages/content/cars.html
- content_upload.go
- go.mod
- go.sum
> added tags input to car upload form

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
> add wait time to session time on live timings

- CHANGELOG.md
- cmd/server-manager/plugins/race-control.lua
- race_control.go
> added onChat function lua plugins

- CHANGELOG.md
- cmd/server-manager/typescript/src/Font.ts
- cmd/server-manager/views/pages/custom-race/index.html
- race_manager.go
> use an even car split when any available car is selected

- CHANGELOG.md
- cmd/server-manager/typescript/src/RaceControl.ts
> show days on live timings timer

- CHANGELOG.md
- race_weekend.go
> make RaceWeekend.Championship nil before duplicating it

- CHANGELOG.md
- race_weekend.go
> race weekend sessions with multiple parents now filter out any duplicate entrants, keeping the entrant with the lowest sort position
